# Generated by Django 4.2.7 on 2025-06-25 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devEUI', models.CharField(help_text='Device EUI identifier', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latest_status', models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing')], default='failing', help_text='Latest status based on most recent payload', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fCnt', models.BigIntegerField(help_text='Frame counter for duplicate detection')),
                ('data', models.TextField(help_text='Base64 encoded data')),
                ('data_hex', models.CharField(help_text='Hexadecimal representation of data', max_length=500)),
                ('status', models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing')], help_text='Status determined from data value', max_length=10)),
                ('raw_payload', models.JSONField(help_text='Original payload received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(help_text='Device this payload belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='iot_devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('device', 'fCnt')},
            },
        ),
    ]
